name: Finance
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  mask_text_input_formatter: ^2.9.0
  go_router: ^14.2.8
  get_it: ^8.0.0
  easy_localization: ^3.0.7
  repo_annotation:
    git:
      url: https://github.com/gitformannon/Finance.git
      path: mobile_frontend
  retrofit: ^4.4.1
  logger: ^2.4.0  # for logging purpose
  json_annotation: ^4.9.0
  dio: ^5.7.0
  flutter_bloc: ^8.1.6
  freezed_annotation: ^2.4.4
  equatable: ^2.0.5
  shimmer: ^3.0.0
  flash: ^3.1.1
  hive: ^2.2.3
  cached_network_image: ^3.4.0
  flutter_native_splash: ^2.4.0
  path_provider: ^2.1.4
  flutter_screenutil: ^5.9.3
  loading_animation_widget: ^1.3.0
  currency_text_input_formatter: ^2.2.9
  dartz: ^0.10.1
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  retrofit_generator: '>=8.0.0 <10.0.0' # for Dart 3.3 use ^9.0.0
  build_runner: ^2.4.9
  json_serializable: ^6.8.0
  repo_generation:
    git:
      url: https://github.com/gitformannon/Finance.git
      path: mobile_frontend
  freezed: ^2.5.2
flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/png/
    - assets/font/
    - assets/locale/
    - assets/

  fonts:
    - family: fontBold
      fonts:
        - asset: assets/font/Poppins-Bold.ttf
          weight: 900
    - family: fontMedium
      fonts:
        - asset: assets/font/Poppins-Medium.ttf
          weight: 500
    - family: fontSemiBold
      fonts:
        - asset: assets/font/Poppins-SemiBold.ttf
          weight: 600
    - family: fontRegular
      fonts:
        - asset: assets/font/Poppins-Regular.ttf
          weight: 400
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/png/logo_launchpad.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter_native_splash:
  color: "#ffffff"
  #  color_dark: "#111111"
  color_dark: "#ffffff"
  image: assets/png/logo_launchpad.png
  image_dark: assets/png/logo_launchpad.png
  fullscreen: true
  android_12:
    image: logo_launchpad.png
    image_dark: logo_launchpad.png
    icon_background_color: "#ffffff"

